{% set version = "4.3.2" %}

package:
  name: cutlass
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cutlass/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e84ccd6b0c749ca87a845fb57df3d8898257bda404c5bc93ad0fb51d6decf54d

build:
  number: 0
  skip: true  # [osx]
  ignore_run_exports_from:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - ninja-base

test:
  commands:
    - test -d $PREFIX/include/cutlass            # [linux]
    - test -d $PREFIX/include/cute               # [linux]
    - test -d $PREFIX/lib/cmake                  # [linux]
    - if not exist %LIBRARY_INC%\cutlass exit 1  # [win]
    - if not exist %LIBRARY_INC%\cute exit 1     # [win]
    - if not exist %LIBRARY_LIB%\cmake exit 1    # [win]

about:
  home: https://github.com/NVIDIA/cutlass
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: CUDA Templates for Linear Algebra Subroutines
  description: |
    CUTLASS is a collection of abstractions for implementing high-performance matrix-matrix multiplication (GEMM) and
    related computations at all levels and scales within CUDA. It incorporates strategies for hierarchical decomposition
    and data movement. CUTLASS decomposes these "moving parts" into reusable, modular software components and abstractions.
  doc_url: https://docs.nvidia.com/cutlass/latest/overview.html
  dev_url: https://github.com/NVIDIA/cutlass

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - h-vetinari
    - RaulPPelaez
    - leofang
